FROM mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04

USER root
RUN mkdir -p /out
RUN chown mssql /out
USER mssql

WORKDIR /working
COPY scripts/shared/*.sh ./
COPY scripts/create-bak/*.sh ./
COPY *.sql ./

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=weakPASSw0rd

# Needs environment variables set up;
# https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
RUN /bin/bash -c "./ci-entry.sh"

CMD /bin/bash -c "cp -R /out/* /src"
